name: Deploy VS Code Extension

on:
  push:
    tags:
      - "vscode-extension-v[0-9]+.[0-9]+.[0-9]+"
  workflow_dispatch:

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  deploy:
    name: Deploy to VS Code Marketplace
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: vscode-extension
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v7

      - name: Use Node.js 24.x
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Install Dependencies
        run: npm ci

      - name: Compile
        run: npm run compile

      - name: Publish to VS Code Marketplace
        run: npx @vscode/vsce publish
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
