name: Test

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - main
      - next
  push:
    branches:
      - main
      - next

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Use Node.js 24.x
        uses: actions/setup-node@v6
        with:
          node-version: 24
          registry-url: "https://registry.npmjs.org"

      - run: npm ci

      - name: Build
        run: npm run build

      - name: Test
        run: npm test
